### ISSUE TITLE
groupDetail.html

### ISSUE THREAD

**Issue by KillahDillah** [milaendo/frontEnd-wireframes#2]
![screen shot 2018-09-11 at 4 04 02 pm](https://user-images.githubusercontent.com/29666170/45392466-56e3c380-b5dc-11e8-9fd9-48186cdc80b8.png)

should look like

<img width="480" alt="screen shot 2018-09-11 at 4 05 42 pm" src="https://user-images.githubusercontent.com/29666170/45392522-914d6080-b5dc-11e8-87c8-f2a3ee321607.png">

**Comment by KillahDillah** [comment]
![screen shot 2018-09-11 at 4 04 41 pm](https://user-images.githubusercontent.com/29666170/45392485-69f69380-b5dc-11e8-897f-79f1244ae9ef.png)
Should look like

<img width="1153" alt="screen shot 2018-09-11 at 4 05 03 pm" src="https://user-images.githubusercontent.com/29666170/45392507-82ff4480-b5dc-11e8-8518-2a4cb178846c.png">

**Comment by milaendo** [comment]
![screen shot 2018-09-12 at 9 24 14 am](https://user-images.githubusercontent.com/29641725/45439053-ae7e3f80-b66d-11e8-9550-7a25a99359b8.png)
