### ISSUE TITLE
userDetail.html

### ISSUE THREAD

**Issue by KillahDillah** [milaendo/frontEnd-wireframes#4]
![screen shot 2018-09-11 at 4 12 21 pm](https://user-images.githubusercontent.com/29666170/45392707-7b8c6b00-b5dd-11e8-9181-46b227ece36f.png)

Status bubble looks too large

<img width="231" alt="screen shot 2018-09-11 at 4 12 40 pm" src="https://user-images.githubusercontent.com/29666170/45392718-86470000-b5dd-11e8-92fd-e9462071b419.png">

**Comment by milaendo** [comment]
![screen shot 2018-09-12 at 9 11 47 am](https://user-images.githubusercontent.com/29641725/45438469-1469c780-b66c-11e8-93de-9426b4679b0b.png)
